spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://172.17.0.2:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
#    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
#    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml


